require("rhhenvim.remap")
require("rhhenvim.packer")
require("rhhenvim.incline")
require("rhhenvim.lualine")
require("rhhenvim.treesitter")
require("rhhenvim.noice")
require("rhhenvim.lsp")
-- require("rhhenvim.netrw")
require("rhhenvim.dash")

-- ColorSchemes
-- require("rhhenvim.rose-pine")
-- require("rhhenvim.atom")
require("rhhenvim.archery")
-- require("rhhenvim.minimalist")
-- require("rhhenvim.tokyonight")
